### ISSUE TITLE
additional networkLite functionality already implemented

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/networkLite#1]
A slightly fuller `networkLite` implementation can be found here:

https://github.com/EpiModel/EpiModel/blob/73d8ae96abea5326902f202c91ee9e5c0a006e7a/R/networkLite.R

with slightly fuller tests here:

https://github.com/EpiModel/EpiModel/blob/73d8ae96abea5326902f202c91ee9e5c0a006e7a/tests/testthat/test-networkLite.R

This additional functionality requires new `network` generics in `network@master`.  If/when those make it to CRAN, this additional `networkLite` functionality could also be pushed to CRAN.  Until then, it resides in the `EpiModel` github history linked to above, should anyone need it.

**Comment by krivit** [comment]
@chad-klumb  since the new `newtork` generics are now out, would you like to do the honours? I can copy the files over, but I'd rather you do it to have an accurate contribution history.
