### ISSUE TITLE
Notes from CRAN v1.0.0 Submission

### ISSUE THREAD

**Issue by smjenness** [EpiModel/networkLite#7]
Please use only undirected quotation marks in the description text.
e.g. `network` --> 'network'

Please always write package names, software names and API (application 
programming interface) names in single quotes in title and description.
e.g: --> 'EpiModel'; 'statnet'
Please note that package names are case sensitive.

If there are references describing the methods in your package, please 
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <[https:...](https://.../)>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for 
auto-linking. (If you want to add a title as well please put it in 
quotes: "Title")

Please add \value to .Rd files regarding exported methods and explain 
the functions results in the documentation. Please write about the 
structure of the output (class) and also what the output means. (If a 
function does not return a value, please document that too, e.g. 
\value{No return value, called for side effects} or similar)
Missing Rd-tags in up to 11 .Rd files, e.g.:
      add_edges.Rd: \value
      add_vertices.Rd: \value
      atomize.Rd: \value
      delete_edges.Rd: \value
      delete_vertices.Rd: \value
      edgecount.Rd: \value
      ...

**Comment by smjenness** [comment]
@chad-klumb : could you handle the documentation issue (last paragraph)? I will handle the others. Thanks!

**Comment by chad-klumb** [comment]
will do

**Comment by chad-klumb** [comment]
addressed in 36f5af0d85f213ac59be259c21a5e3e7fd2f7b2a

**Comment by chad-klumb** [comment]
addressed in 34713ae37024f768d02d68cde955c156f58249ec

**Comment by smjenness** [comment]
We are on CRAN! 

https://cran.r-project.org/package=networkLite
